### ISSUE TITLE
Invalid Report when I try to create `aws-ec2-cluster-cost`

### ISSUE THREAD

**Issue by nut-abctech** [operator-framework/operator-metering#1010]
I enable AWS report and I want to test running report given 
```
apiVersion: metering.openshift.io/v1
kind: Report
metadata:
  name: aws-ec2-cluster-cost-run-once
spec:
  query: "aws-ec2-cluster-cost"
  reportingStart: "2019-10-01T00:00:00Z"
  reportingEnd: "2019-10-31T00:00:00Z"
```
This gives error 
`failed to validate ReportQuery dependencies aws-ec2-cluster-cost: ReportQueryDependencyValidationError: uninitialized ReportDataSource dependencies: aws-billing, aws-ec2-billing-data-raw`

I can not integrate with AWSBillreport because my account is linked account. That why I wanna run it as schudler or once to get usage information
