### ISSUE TITLE
Unable to install on Openshift3.11

### ISSUE THREAD

**Issue by sreekanth-ragi** [operator-framework/operator-metering#1051]
Hi Team,

I've been trying to install on OKD 3.11 cluster with no success using the openshift-install script, I can only get as far as getting the metering pod up, the rest of the pods do not come up.

```
oc get pods
NAME                                READY     STATUS    RESTARTS   AGE
metering-operator-594fccbd5-bzwch   2/2       Running   0          3h

```
```
oc get pods -n olm
NAME                                READY     STATUS    RESTARTS   AGE
catalog-operator-7598c7cf5c-jqfrp   1/1       Running   4          24d
olm-operator-6bc87df958-fdqcg       1/1       Running   4          24d
operatorhubio-catalog-6564b         1/1       Running   4          24d
packageserver-5bd98b477b-4ksfj      1/1       Running   0          3d
packageserver-5bd98b477b-f86h7      1/1       Running   0          3d
```

Here is the custom yaml that I'm suing.
```
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      config:
        prometheusURL: "http://prometheus-k8s.openshift-monitoring.svc:9091"
        tls:
          enabled: false
        metricsTLS:
          enabled: false
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "150Mi"
          cpu: "100m"
  presto:
    spec:
      presto:
        securityContext:
          fsGroup: 0
        coordinator:
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
        worker:
          replicas: 0
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
      hive:
        securityContext:
          fsGroup: 0
        metastore:
          resources:
            requests:
              memory: "650Mi"
              cpu: "500m"
            limits:
              memory: "650Mi"
              cpu: "500m"
          storage:
            create: true
            # Default to null, which means using the default storage class
            class: null
            size: "5Gi"
        server:
          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "100m"
  hdfs:
    spec:
      securityContext:
        fsGroup: 0
      datanode:
        replicas: 1
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "250Mi"
            cpu: "250m"
        storage:
          # Default to null, which means using the default storage class
          class: null
          size: "5Gi"
      namenode:
        resources:
          requests:
            memory: "350Mi"
            cpu: "250m"
          limits:
            memory: "350Mi"
            cpu: "250m"
        storage:
          # Default to null, which means using the default storage class
          class: null
          size: "5Gi"
```
Appreciate all the help provided.

Thanks
Sreekanth

**Comment by timflannagan1** [comment]
What do the metering-operator logs look like?

Please note, we do not support running operator-metering on pre-4.2 releases.

**Comment by sreekanth-ragi** [comment]
@timflannagan1 
Thanks for the reply Tim, I understand that it is not supported pre 4.2 release, but I also saw that others were able to install it successfully on 3.11 openshift so was hopeful I will be able to run it too.

The logs for operator container are as follows.

oc logs po/metering-operator-594fccbd5-bzwch -c operator
```
Adding user ansible-operator with current UID 1000310000 to /etc/passwd
{"level":"info","ts":1575882323.0926185,"logger":"cmd","msg":"Go Version: go1.13.1"}
{"level":"info","ts":1575882323.0927174,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1575882323.0927227,"logger":"cmd","msg":"Version of operator-sdk: v0.12.0+git"}
{"level":"info","ts":1575882323.0927665,"logger":"cmd","msg":"Watching namespace.","Namespace":"openshift-metering"}
{"level":"info","ts":1575882326.4986742,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":1575882326.500422,"logger":"watches","msg":"Failed to parse %v from environment. Using default %v","WORKER_METERINGCONFIG_METERING_OPENSHIFT_IO":1}
{"level":"info","ts":1575882326.5004659,"logger":"watches","msg":"Failed to parse %v from environment. Using default %v","ANSIBLE_VERBOSITY_METERINGCONFIG_METERING_OPENSHIFT_IO":2}
{"level":"info","ts":1575882326.5005322,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"metering.openshift.io","Options.Version":"v1","Options.Kind":"MeteringConfig"}
{"level":"info","ts":1575882326.5010514,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"meteringconfig-controller","source":"kind source: metering.openshift.io/v1, Kind=MeteringConfig"}
{"level":"info","ts":1575882326.5013173,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1575882329.9259064,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1575882329.9259732,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1575882333.3300838,"logger":"cmd","msg":"Could not generate and serve custom resource metrics","Namespace":"openshift-metering","error":"discovering resource information failed for MeteringConfig in metering.openshift.io/v1: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request, servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request"}
{"level":"info","ts":1575882336.7778356,"logger":"metrics","msg":"Metrics Service object updated","Service.Name":"metering-ansible-operator-metrics","Service.Namespace":"openshift-metering"}
{"level":"info","ts":1575882336.7802784,"logger":"proxy","msg":"Starting to serve","Address":"127.0.0.1:8888"}
{"level":"info","ts":1575882336.7805467,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1575882336.880757,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"meteringconfig-controller"}
{"level":"info","ts":1575882336.9810462,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"meteringconfig-controller","worker count":1}
```

And the logs from the ansible container are as follows.
```
oc logs po/metering-operator-594fccbd5-bzwch -c ansible
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
```

Appreciate your time and efforts on helping with this.

Thanks.

**Comment by timflannagan1** [comment]
It looks like you're using the master branch, in which case you need to update a couple of things:

```yaml
apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
...
```
