### ISSUE TITLE
presto can't insert data

### ISSUE THREAD

**Issue by woodliu** [operator-framework/operator-metering#1122]
After install metering, I check the logs of `reporting-operator`，it shows error:   `io.prestosql.spi.PrestoException: Failed checking path: file:/user/hive/warehouse/metering.db/datasource_metering_persistentvolumeclaim_request_bytes`
Then i try a test. In Hive i create a table and insert data to the table ,it's successful. I check this table from Prosto, i can see it. But when i insert data in it，it return the same error like:  
```
presto:metering> INSERT INTO kwang_test VALUES (1, 'San Francisco');
Query 20200306_063214_01963_k6i59 failed: Failed checking path: file:/user/hive/warehouse/metering.db/kwang_test
```

This is my configuration:
```
apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  tls:
    enabled: false
  presto:
    spec:
      coordinator:
        resources:
          limits:
            cpu: 6
            memory: 6Gi
          requests:
            cpu: 4
            memory: 4Gi
  storage:
    type: "hive"
    hive:
      type: "sharedPVC"
      sharedPVC:
        claimName: "reporting-operator-pvc"
```
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reporting-operator-pvc
  namespace: metering
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 95Gi
```

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: operator-metering-pv
  labels:
    name: operator-metering
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/metering/hive-metastore"
  persistentVolumeReclaimPolicy: Delete
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
```
I use a local filesystem to create pvc as the Hive storage.
Anyone help, thanks a lot !

**Comment by timflannagan1** [comment]
I haven't played around with using a ReadWriteMany PVC for metastore storage in a while, but you may want to try updating your `MeteringConfig` custom resource and explicitly specifying the mount path for that volume (as the default is `/user/hive/warehouse/metering.db`):

```yaml
hive:
  storage:
    type: "sharedPVC"
    sharedPVC:
      claimName: "reporting-operator-pvc"
      mountPath: "/mnt/metering/hive-metastore"
```

I can try re-creating your setup later and report back.

**Comment by woodliu** [comment]
> I haven't played around with using a ReadWriteMany PVC for metastore storage in a while, but you may want to try updating your `MeteringConfig` custom resource and explicitly specifying the mount path for that volume (as the default is `/user/hive/warehouse/metering.db`):
> 
> ```yaml
> hive:
>   storage:
>     type: "sharedPVC"
>     sharedPVC:
>       claimName: "reporting-operator-pvc"
>       mountPath: "/mnt/metering/hive-metastore"
> ```
> 
> I can try re-creating your setup later and report back.

Thank you for replying. I have tried，but it still not work....

**Comment by timflannagan1** [comment]
Hmm okay, you may need to uninstall and then reinstall again as changes made post-installation to any storage configuration typically don't propagate.

**Comment by woodliu** [comment]
> Hmm okay, you may need to uninstall and then reinstall again as changes made post-installation to any storage configuration typically don't propagate.

Yeah, When uninstall, I allways clean all the data, include all pv and pvc, and the data in the pvs.

**Comment by woodliu** [comment]
I think the issue may be related with the presto.....

**Comment by timflannagan1** [comment]
The metering-operator pulls container images from that get built from the `operator-framework/presto` repository, which is just a fork of the upstream `prestosql/presto` repository.

**Comment by woodliu** [comment]
@timflannagan1 could you tell me how to build a new presto with new version of `prestosql/presto`？ Thank you

**Comment by timflannagan1** [comment]
I recent built and pushed a more up-to-date Presto image using the 328 version (330 is the most recent, releaseed version) under the `quay.io/tflannag/presto:release-328` tag, and you would need to override the metering-operator image to point to the `quay.io/tflannag/origin-metering-ansible-operator:release-328` too:

```bash
export METERING_OPERATOR_IMAGE_REPO=quay.io/tflannag/origin-metering-ansible-operator
export METERING_OPERATOR_IMAGE_TAG=release-328
```

 If you're interested in using that image, you would need to update the `MeteringConfig` custom resource file to specify that repository and tag, e.g.:

```yaml
apiVersion: metering.openshift.io/v1
kind: MeteringConfig
...
spec:
...
  presto:
    spec:
      image:
        repository: quay.io/tflannag/presto
        tag: release-328
```

I haven't really played around with that Presto image yet and I had to remove one of the Presto plugin/connectors (presto-prometheus) to make it build properly.

If that doesn't suffice, then in order to do this I had to pull down the 328 release tag (or whatever applicable release tag) from the upstream prestosql/presto repository. I then had to update the `Dockerfile.okd`, adding of the new directories in the repository that were highlighted as errors when attempted to buidl this new image via `docker build -f Dockerfile.okd <image>:<tag> .`. 

Here is the full diff of that Dockerfile (with same lazy workarounds like hardcoding the presto version):

```diff
tflannag@localhost presto [cherry-pick-hive-metastore-s3-fix]  git diff Dockerfile.okd
diff --git a/Dockerfile.okd b/Dockerfile.okd
index a35f9a4554..d63571804e 100644
--- a/Dockerfile.okd
+++ b/Dockerfile.okd
@@ -44,7 +44,6 @@ COPY presto-record-decoder /build/presto-record-decoder
 COPY presto-tpcds /build/presto-tpcds
 COPY presto-plugin-toolkit /build/presto-plugin-toolkit
 COPY presto-spi /build/presto-spi
-COPY presto-prometheus /build/presto-prometheus
 COPY presto-thrift-testing-server /build/presto-thrift-testing-server
 COPY presto-cli /build/presto-cli
 COPY presto-hive /build/presto-hive
@@ -75,7 +74,10 @@ COPY presto-kudu /build/presto-kudu
 COPY presto-main /build/presto-main
 COPY presto-raptor-legacy /build/presto-raptor-legacy
 COPY presto-password-authenticators /build/presto-password-authenticators
+COPY presto-memsql /build/presto-memsql
+COPY presto-testing /build/presto-testing
 COPY src /build/src
+COPY src/modernizer/violations.xml /build/src/modernized/violations.xml
 COPY pom.xml /build/pom.xml
 
 # build presto
@@ -103,7 +105,7 @@ RUN chmod +x /usr/bin/tini
 
 RUN mkdir -p /opt/presto
 
-ENV PRESTO_VERSION 322
+ENV PRESTO_VERSION 328
 ENV PRESTO_HOME /opt/presto/presto-server
 ENV PRESTO_CLI /opt/presto/presto-cli
 ENV PROMETHEUS_JMX_EXPORTER /opt/jmx_exporter/jmx_exporter.jar
@@ -113,8 +115,8 @@ ENV JAVA_HOME=/etc/alternatives/jre
 
 RUN mkdir -p $PRESTO_HOME
 
-COPY --from=build /build/presto-server/target/presto-server-$PRESTO_VERSION $PRESTO_HOME
-COPY --from=build /build/presto-cli/target/presto-cli-$PRESTO_VERSION-executable.jar $PRESTO_CLI
+COPY --from=build /build/presto-server/target/presto-server-328 $PRESTO_HOME
+COPY --from=build /build/presto-cli/target/presto-cli-328-executable.jar $PRESTO_CLI
 COPY --from=build /build/jmx_prometheus_javaagent.jar $PROMETHEUS_JMX_EXPORTER
tflannag@localhost presto [cherry-pick-hive-metastore-s3-fix]  
```

Here's a link to a local branch that highlights the changes I made: https://github.com/timflannagan1/presto/commit/5b6e1c296911751009e7ead6926531aca09fe171
