### ISSUE TITLE
Custom Prometheus queries and default report queries

### ISSUE THREAD

**Issue by cristi-** [operator-framework/operator-metering#537]
Hi everyone,

We are exploring the metering operator in our infrastructure and it's been great so far! We are now at our first customization and I have a few questions, I hope this is a good place to ask them. 

We need to make a change to the default **ReportPrometheusQuery** for "node-capacity-cpu-cores" (https://github.com/operator-framework/operator-metering/blob/0499dc4e1ba10f1d85edc7c9e2b50a9bc809a46c/charts/openshift-reporting/templates/prom-queries/node-capacity.yaml#L24) . We have a different metric that exposes the provider_id that we need to add here.

1. Should we modify the default 'node-capacity-cpu-cores' ? How would we ensure that on upgrade the promquery would not be overwritten?

2. If we should create a new ReportPrometheusQuery with the new promquery can we attach it to the existing report data source in order for us to use the existing reports ?

Thank you!

**Comment by chancez** [comment]
Can you be more specific about the metric you need that gives you a provider_id? The answer depends a lot on what exactly you actually need and want to do.

**Comment by cristi-** [comment]
Sure, let me try to explain (everyone has custom solutions :) )

We run our kubernetes AWS clusters without the cloud provider feature enabled. Without cloud-provider, there is no instance-id available in metrics.

Here is how the default 'node-capacity-cpu-cores' Prometheus query looks like on our cluster:


![metering_operator_no_id](https://user-images.githubusercontent.com/11157105/50197921-035ae180-0352-11e9-8122-310fb277dc4f.PNG)
No "instance-id" that we can use later.

To work around this issue, we're publishing our own metric named "aws_instance" that is used to link the node name to a aws instance-id. 
This is how the query looks like after adding a new join:
![metering_operator_with_id](https://user-images.githubusercontent.com/11157105/50198208-3ea9e000-0353-11e9-8d87-c0f91f955680.PNG)

All the standard reports work fine after making this change. Unfortunately, we have edited the default 'node-capacity-memory-bytes' Prometheus query with 'kubectl edit'. My question is how could we make this change in a more persistent manner (that works after upgrades/re-installs) ?

Thanks for the help!

**Comment by chancez** [comment]
For this kind of change, the only thing we can truely support at this moment is having you create a separate copy of the resources your modifying that you maintain. If you just create copies of the existing resources that you're modifying and adjust the ReportDataSources and queries you reference to your copies, most things should continue to work as new versions come out.

As we support more chargeback/billing use-cases from other clouds, and baremetal we'll come to a solution that has a better "contract/API" so you can more easily just "provide-your-own" cost correlation metric or fields. It's likely we'll make the table and field you join against for correlation something more parameterizable via ReportGenerationQuery inputs, but to do that we need to see how it works against other cloud billing schemas and find what's in-common between them.

**Comment by cristi-** [comment]
Thank you for the guidance!

I'll leave the configuration we decided on using here, maybe someone else will find it useful:

```
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  openshift-reporting:
    spec:
      awsBillingReportDataSource:
        enabled: true
        bucket: "bucket-costexplorer"
      defaultReportDataSources:
        node-allocatable-memory-bytes:
          spec:
            promsum:
              query: "new-node-allocatable-memory-bytes"
        node-capacity-memory-bytes:
          spec:
            promsum:
              query: "new-node-capacity-memory-bytes"
        node-allocatable-cpu-cores:
          spec:
            promsum:
              query: "new-node-allocatable-cpu-cores"
        node-capacity-cpu-cores:
          spec:
            promsum:
              query: "new-node-capacity-cpu-cores"
```

Then each new ReportPrometheusQuery is stored in a yaml file that's being applied independent of the operator lifecycle, e.g:

```
cat reportpromquery.yaml
---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportPrometheusQuery
metadata:
  labels:
    operator-metering: "true"
  name: new-node-allocatable-cpu-cores
  namespace: metering
spec:
  query: |
    kube_node_status_allocatable_cpu_cores * on(node) group_left(provider_id) max(kube_node_info) by (node, provider_id) * on(node) group_left(provider_id) aws_instance
```

Thanks again! You can close the issue.
