### ISSUE TITLE
hive not connecting to pgsql

### ISSUE THREAD

**Issue by stenwt** [operator-framework/operator-metering#566]
Per the [documentation](https://github.com/operator-framework/operator-metering/blob/master/Documentation/configuring-hive-metastore.md), I am configuring a new install of metering to use a pgsql pod deployed to the same OpenShift project: 

$ oc get svc | grep postgres
postgresql-95-centos7                      ClusterIP   172.31.55.232    <none>        5432/TCP              5d

I then created this config: 

```yaml
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  presto:
    spec:
      hive:
        config:
          dbConnectionURL: "jdbc:postgresql://postgresql-95-centos7:5432/metering"
          dbConnectionDriver: "org.postgresql.Driver"
          dbConnectionUsername: "metering"
          dbConnectionPassword: "my-password-string"
```
Pointed to it with the METERING_CR_FILE environment variable, and ran hack/openshift-install.sh. 

After the install runs, the reporting-operator starts up but never shows ready. The logs for that pod show: 

```
time="2019-01-16T15:49:45Z" level=info msg="adding ReportGenerationQuery pod-memory-request" app=metering
time="2019-01-16T15:49:45Z" level=info msg="adding ReportGenerationQuery pod-memory-request-raw" app=metering
time="2019-01-16T15:49:45Z" level=info msg="adding ReportGenerationQuery pod-memory-request-vs-node-memory-allocatable" app=metering
time="2019-01-16T15:49:45Z" level=info msg="adding ReportGenerationQuery pod-memory-usage" app=metering
time="2019-01-16T15:49:45Z" level=info msg="adding ReportGenerationQuery pod-memory-usage-raw" app=metering
time="2019-01-16T15:49:46Z" level=info msg="starting HTTP server" app=metering
time="2019-01-16T15:49:46Z" level=info msg="testing ability to write to Presto" app=metering
time="2019-01-16T15:49:46Z" level=info msg="HTTP API server listening with TLS on 127.0.0.1:8080" app=metering
time="2019-01-16T15:50:34Z" level=error msg="cannot create Presto table operator_health_check" app=metering component=testWriteToPresto error="timed out waiting for the condition"
time="2019-01-16T15:51:41Z" level=info msg="\"GET https://10.250.10.3:8080/ready HTTP/2.0\" from 10.250.10.1:56882 - 500 50B in 594.958µs" app=metering component=api
time="2019-01-16T15:52:41Z" level=info msg="\"GET https://10.250.10.3:8080/ready HTTP/2.0\" from 10.250.10.1:57172 - 500 50B in 49.564µs" app=metering component=api
time="2019-01-16T15:53:41Z" level=info msg="\"GET https://10.250.10.3:8080/ready HTTP/2.0\" from 10.250.10.1:57456 - 500 50B in 43.356µs" app=metering component=api
time="2019-01-16T15:54:41Z" level=info msg="\"GET https://10.250.10.3:8080/ready HTTP/2.0\" from 10.250.10.1:57754 - 500 50B in 33.625µs" app=metering component=api
```

I encountered this with release-0.11, then noticed .13 was released, and I replicated the problem with 0.13 after deleting and re-creating my project.  The only difference is I don't see the timeout message in .13: 

```
time="2019-01-16T16:13:06Z" level=info msg="testing ability to write to Presto" app=metering
time="2019-01-16T16:13:06Z" level=info msg="HTTP API server listening with TLS on 127.0.0.1:8080" app=metering
time="2019-01-16T16:14:26Z" level=info msg="\"GET https://10.250.10.25:8080/ready HTTP/2.0\" from 10.250.10.1:33732 - 500 50B in 373.63µs" app=metering component=api
time="2019-01-16T16:15:26Z" level=info msg="\"GET https://10.250.10.25:8080/ready HTTP/2.0\" from 10.250.10.1:34030 - 500 50B in 49.415µs" app=metering component=api
time="2019-01-16T16:16:26Z" level=info msg="\"GET https://10.250.10.25:8080/ready HTTP/2.0\" from 10.250.10.1:34332 - 500 50B in 38.505µs" app=metering component=api
time="2019-01-16T16:17:26Z" level=info msg="\"GET https://10.250.10.25:8080/ready HTTP/2.0\" from 10.250.10.1:34626 - 500 50B in 40.387µs" app=metering component=api
time="2019-01-16T16:18:26Z" level=info msg="\"GET https://10.250.10.25:8080/ready HTTP/2.0\" from 10.250.10.1:34922 - 500 50B in 42.805µs" app=metering component=api
time="2019-01-16T16:19:26Z" level=info msg="\"GET https://10.250.10.25:8080/ready HTTP/2.0\" from 10.250.10.1:35224 - 500 50B in 43.796µs" app=metering component=api
time="2019-01-16T16:20:26Z" level=info msg="\"GET https://10.250.10.25:8080/ready HTTP/2.0\" from 10.250.10.1:35530 - 500 50B in 43.522µs" app=metering component=api
time="2019-01-16T16:20:49Z" level=info msg="got signal terminated, performing shutdown"
```

If I shell into the postgres pod, I do see that the operator has created a schema: 

```
postgres=# \c metering
You are now connected to database "metering" as user "postgres".
metering=# \dt
                   List of relations
 Schema |           Name            | Type  |  Owner
--------+---------------------------+-------+----------
 public | BUCKETING_COLS            | table | metering
 public | CDS                       | table | metering
 public | COLUMNS_V2                | table | metering
 public | DATABASE_PARAMS           | table | metering
 [snip]
```

So I at least got my DB connection parameters right.

**Comment by chancez** [comment]
Can you check the hive metastore, hive server, and presto logs to see if there are any errors?

**Comment by stenwt** [comment]
[reporting-logs-debug.txt](https://github.com/operator-framework/operator-metering/files/2828624/reporting-logs-debug.txt)

If I'm reading this right, reporting-operator is trying to connect to service presto:8080, which fails. If I rsh to the reporting-operator pod and curl presto:8080 I get a http 301 response, which sounds like it's working. That may have been transient, while the presto pod came up. 

There are several failures in the hive-server-0 log as it tries and fails to connect to hive-metastore, but, likely after the metastore pod comes up, those messages stop and the last message looks like a successful connection. 

I note this in the hive-metastore-0 log: 

19/02/04 15:14:12 [pool-7-thread-7]: WARN metastore.HiveMetaStore: Location: hdfs://hdfs-namenode-proxy:9820/operator_metering/storage/metering_health_check specified for non-external table:operator_health_check

that seems related to the test that's failing from the reporting-operator. 

It also looks like metastore is successfylly connected to postgres: 

19/02/04 15:19:49 [pool-7-thread-25]: INFO metastore.ObjectStore: ObjectStore, initialize called
19/02/04 15:19:49 [pool-7-thread-25]: INFO metastore.MetaStoreDirectSql: Using direct SQL, underlying DB is POSTGRES
19/02/04 15:19:49 [pool-7-thread-25]: INFO metastore.ObjectStore: Initialized ObjectStore

This makes it sound like an issue with my config? But if that's the case, I'm not sure how to correct it.

**Comment by stenwt** [comment]
`$ oc get pods
NAME                                  READY     STATUS    RESTARTS   AGE
hdfs-datanode-0                       1/1       Running   0          30m
hdfs-namenode-0                       1/1       Running   0          30m
hive-metastore-0                      1/1       Running   0          30m
hive-server-0                         1/1       Running   0          30m
metering-operator-558d78b4cf-7jq29    2/2       Running   0          31m
postgresql-95-centos7-2-zjmsb         1/1       Running   0          1h
presto-coordinator-66b7fc44fc-xh9mg   1/1       Running   0          30m
reporting-operator-655889659d-979mn   0/1       Running   3          30m
$ oc get services
NAME                                                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)               AGE
glusterfs-dynamic-hdfs-datanode-data-hdfs-datanode-0   ClusterIP   172.31.171.154   <none>        1/TCP                 59m
glusterfs-dynamic-hdfs-namenode-data-hdfs-namenode-0   ClusterIP   172.31.237.198   <none>        1/TCP                 59m
glusterfs-dynamic-hive-metastore-db-data               ClusterIP   172.31.57.27     <none>        1/TCP                 59m
glusterfs-dynamic-pvc-t8q8l                            ClusterIP   172.31.154.179   <none>        1/TCP                 1h
hdfs-datanode                                          ClusterIP   None             <none>        9866/TCP              31m
hdfs-datanode-web                                      ClusterIP   172.31.103.5     <none>        9864/TCP              31m
hdfs-namenode                                          ClusterIP   None             <none>        9820/TCP              31m
hdfs-namenode-proxy                                    ClusterIP   172.31.233.164   <none>        9820/TCP              31m
hdfs-namenode-web                                      ClusterIP   172.31.108.176   <none>        9870/TCP              31m
hive-metastore                                         ClusterIP   172.31.215.221   <none>        9083/TCP              31m
hive-server                                            ClusterIP   172.31.3.254     <none>        10000/TCP,10002/TCP   31m
postgresql-95-centos7                                  ClusterIP   172.31.231.134   <none>        5432/TCP              1h
presto                                                 ClusterIP   172.31.115.137   <none>        8080/TCP              31m
presto-metrics                                         ClusterIP   172.31.1.156     <none>        8082/TCP              31m
reporting-operator                                     ClusterIP   172.31.196.87    <none>        8080/TCP              31m
reporting-operator-metrics                             ClusterIP   172.31.7.50      <none>        8082/TCP              31m
`
in case that helps line up pod/ port/ip/service

**Comment by chancez** [comment]
According to the logs this is hitting a known issue where hive-server is getting a "No route to host" error when talking to hive-metastore. Try deleting the hive-server-0 pod, and it will automatically be re-created and that typically allows it to connect. We're still investigating the underlying cause for this.

**Comment by chancez** [comment]
So now it's getting read timeouts. You can't currently adjust the timeout for hive-server talking to metastore (not configurable yet), but you can likely increase the amount of resources you give to hive-metastore. 

https://github.com/operator-framework/operator-metering/blob/master/Documentation/tuning.md covers increasing resource limits.

**Comment by stenwt** [comment]
I had applied my own tunings: 

```
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      resources:
        requests:
          memory: "300Mi"
          cpu: "50m"
        limits:
          memory: "300Mi"
          cpu: "100m"
  presto:
    spec:
      hive:
        config:
          dbConnectionURL: "jdbc:postgresql://postgresql-95-centos7:5432/metering"
          dbConnectionDriver: "org.postgresql.Driver"
          dbConnectionUsername: "metering"
          dbConnectionPassword: "my-password-string"
      presto:
        coordinator:
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
        worker:
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
```

Now I'm adding my postgres config parameters to the recommended-resource-limits, and setting datanode replicas to 1 since we only have one compute node available in our lab, but otherwise I'm using it verbatim: 

https://raw.githubusercontent.com/operator-framework/operator-metering/master/manifests/metering-config/recommended-resource-limits.yaml

I tore down my metering project and re-created it with that config. I'm still getting timeouts from hive-metastore: 
[hive-server.log](https://github.com/operator-framework/operator-metering/files/2834081/hive-server.log)

Is it worth it to embiggen hive-metastore even more?
