### ISSUE TITLE
Issue retrieving billing data

### ISSUE THREAD

**Issue by jaxxstorm** [operator-framework/operator-metering#594]
I have the billing configuration set up with consolidated billing. Here's my `metering-custom.yaml`

```
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  openshift-reporting:
    spec:
      awsBillingReportDataSource:
        enabled: true
        # Replace these with where your AWS billing reports are
        # stored in S3.
        bucket: "<consolidated billing bucket>"
        prefix: "/path"
        region: "us-east-1"
  defaultStorage:
    create: true
    name: "s3"
    isDefault: true
    type: "hive"
    hive:
      tableProperties:
        # update this with the name of your bucket and the path within
        # that bucket you wish to use. Do not change the s3a:// protocol.
        location: "s3a://bucket/location"
  reporting-operator:
    spec:
      resources:
        requests:
          memory: "2Gi"
          cpu: "4"
        limits:
          memory: "2Gi"
          cpu: "4"
      config:
        awsAccessKeyID: "REDACTED"
        awsSecretAccessKey: "REDACTED"
        prometheusURL: "http://prometheus-k8s.monitoring.svc.cluster.local:9090/"
        tls:
          enabled: false
        metricsTLS:
          enabled: false
  presto:
    spec:
      presto:
        securityContext:
          fsGroup: 0
        coordinator:
          resources:
            requests:
              memory: "4Gi"
              cpu: "4"
            limits:
              memory: "4Gi"
              cpu: "4"
        worker:
          replicas: 0
          resources:
            requests:
              memory: "4Gi"
              cpu: "4"
            limits:
              memory: "4Gi"
              cpu: "4"
      config:
        awsAccessKeyID: "REDACTED"
        awsSecretAccessKey: "REDACTED"
      hive:
        hive:
        metastore:
          resources:
            requests:
              memory: "2Gi"
              cpu: "4"
            limits:
              memory: "2Gi"
              cpu: "4"
        config:
          useHdfsConfigMap: false
        securityContext:
          fsGroup: 0
  hdfs:
    enabled: false
```

I then defined a report like so:

```
apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: pod-cpu-request-hourly-billing
  namespace: metering
spec:
  generationQuery: "pod-cpu-request-aws"
  gracePeriod: "5m"
  schedule:
    period: "hourly"
```

When I try to query the report, I get the following error:

```
{"error":"report is is failed state, reason: GenerateReportError, message: error occurred while generating report: Failed to execute query pod-cpu-request-aws for Report table report_metering_pod_cpu_request_hourly_billing: presto: query failed (200 OK): \"com.facebook.presto.sql.analyzer.SemanticException: line 19:6: Table hive.default.view_metering_aws_ec2_billing_data_raw does not exist\""}%
```

Did I misconfigure something?

**Comment by chancez** [comment]
I think there's a bug in the yaml rendering after testing it. Our testing is unfortunately in a place where it's difficult to test this feature but we're working on that. I'm testing a fix now, seems like a simple issue.

**Comment by jaxxstorm** [comment]
awesome, will we get a new release for the bug, or will I have to compile it?

**Comment by chancez** [comment]
Actually, after testing, I was able to do it with no modifications, using a similar config. Can you check the reporting-operator logs?

**Comment by jaxxstorm** [comment]
Looks like my path is incorrect?

```
time="2019-02-26T22:06:44Z" level=error msg="error syncing ReportDataSource \"metering/aws-billing\", adding back to queue" ReportDataSource=metering/aws-billing app=metering component=reportDataSourceWorker error="can't get manifest from bucket 'bucket' with key '/Path/20170701-20170801/Path.json': NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: B4C6096CF0B9DE7D, host id: twysoOV8MAHXQ3ooXz5xwfJtYYXcKRsaDShZ2pP1PQ7jmjfg+9a/7DVE7KgngfpnzmnwQr676D8=" logID=GgOg4o268J
``

**Comment by jaxxstorm** [comment]
I think this is related to #581 

When trying to specify this against consolidated billing, it seems the path needs to be set in JSON, and we specified text/csv

Just a question, the path

```
prefix: "/path"
```

Should be set to the path in the report path, right?

**Comment by chancez** [comment]
There's generally a JSON file that has metadata about the CSV files.

Here's a config we're using:

<img width="1207" alt="screen shot 2019-02-26 at 2 52 20 pm" src="https://user-images.githubusercontent.com/1400401/53452672-d3c1f880-39d6-11e9-8e6e-640581a3934e.png">

With this:
```
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  openshift-reporting:
    spec:
      awsBillingReportDataSource:
        enabled: true
        bucket: "coreos-reporting"
        prefix: "coreos-detailed-billing/coreosinc/coreos-detailed-billing-001"
        region: "us-east-1"

...
```
