### ISSUE TITLE
Getting historical prometheus data

### ISSUE THREAD

**Issue by jaxxstorm** [operator-framework/operator-metering#597]
I'm trying to understand the reporting interface, sorry for all the questions.

Is it true that if I specify time in the past (for which I have prom metrics) but BEFORE the report operator was installed, I can generate a report for historical metrics?

```
apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: namespace-cpu-request
spec:
  reportingStart: '2019-01-01T00:00:00Z'
  reportingEnd: '2019-01-30T23:59:59Z'
  generationQuery: "namespace-cpu-request"
  runImmediately: true
```

Would this generate report data for the whole month of Jan, even if the operator wasn't installed?
