### ISSUE TITLE
How can I use "Conditional statements" in ReportGenerationQuery ?

### ISSUE THREAD

**Issue by JooyoungJeong** [operator-framework/operator-metering#616]
Hi.
 

I used "Conditional statements" (if/else if /else)  in  ReportGenerationQuery . 
but there is error. 

I don't know how to use conditaional statements in ReportGenerationQuery.

```
 Message:               error occurred while generating report: error parsing query: template: report-generation-query:1: unexpected "=" in operand
```

```  yaml
apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  labels:
    operator-metering: "true"
  name: report-test
  namespace: metering
spec:
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: element
    type: string
    unit: element
  - name: cluster
    tableHidden: false
    type: string
    unit: kubernetes_cluster
  - name: region
    tableHidden: false
    type: string
    unit: kubernetes_region
  - name: value
    type: double
    unit: percent
  inputs:
  - name: ReportingStart
  - name: ReportingEnd
  - name: PeriodName
  query: |
    {|- if .Report.Inputs.PeriodName == "daily"-|}
    select 
    cast(dt as timestamp) as period_start,
    cast(dt as timestamp) as period_end,
    gpupool as element,
    cluster,
    region,
    gpu_request/gpu_capacity * 100 as value
    from {| reportTableName  "report-test-gpu-capacity-request-gpupool-daily" |}
    {|- else if .Report.Inputs.PeriodName == "weekly"-|}
    select 
    min(cast(dt as timestamp)) as period_start,
    max(cast(dt as timestamp)) as period_end,
    gpupool as element,
    cluster,
    region,
    sum(gpu_request)/sum(gpu_capacity) * 100 as value
    from {| reportTableName  "report-test-gpu-capacity-request-gpupool-daily" |}
    group by week(cast(dt as timestamp)),gpupool,cluster,region
    {|- else if .Report.Inputs.PeriodName == "monthly"-|}
    select 
    min(cast(dt as timestamp)) as period_start,
    max(cast(dt as timestamp)) as period_end,
    gpupool,
    cluster,
    region,
    sum(gpu_request)/sum(gpu_capacity) * 100 as value
    from {| reportTableName  "report-test-gpu-capacity-request-gpupool-daily" |}
    group by week(cast(dt as timestamp)),gpupool,cluster,region
    {|- end -|}
  reportDataSources:
  - mlp-gpu-capacity-slots
  view:
    disabled: true
---
apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: report-test-daily
spec:
  generationQuery: "report-test"
  schedule:
    period: "hourly"
  reportingStart: "2019-02-28T00:00:00Z"
  gracePeriod: "10m"
  inputs:
  - name: PeriodName
    value: daily
  overwriteExistingData: true
---
apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: report-test-weekly
spec:
  generationQuery: "report-test"
  schedule:
    period: "daily"
  reportingStart: "2019-02-28T00:00:00Z"
  gracePeriod: "10m"
  inputs:
  - name: PeriodName
    value: weekly
  overwriteExistingData: true
---
apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: report-test-monthly
spec:
  generationQuery: "report-test"
  schedule:
    period: "daily"
  reportingStart: "2019-02-28T00:00:00Z"
  gracePeriod: "10m"
  inputs:
  - name: PeriodName
    value: monthly
  overwriteExistingData: true

```

Thank you.

**Comment by chancez** [comment]
Inside the `spec.query` field you have full access to go text/templates https://golang.org/pkg/text/template/, so you should use these documents for the nuances of templating. You'll likely want to use `eq` for comparisons.

**Comment by chancez** [comment]
Also I'm interested in your template! I've had a lot of similar ideas of what you're trying to achieve and wonder if we could improve things at all. It looks like you're running periodically, but computing a rolling window of results?

**Comment by JooyoungJeong** [comment]
ex. 
```
{|- if ( .Report.Inputs.PeriodName ) and eq .Report.Inputs.PeriodName "daily" -|}
{|- else if eq .Report.Inputs.PeriodName  "weekly" -|}
{|- end -|}
```
@chancez  Thank you for your feedback:)

However, if this conditional is included in the middle of the query, the query did not work as I thought. So I constructed the query in the following way.

```
with today AS (
    select
       ...
    from {| dataSourceTableName .Report.Inputs.SourceTable |}
    where labels['timestamp'] >=  cast( current_date  as VARCHAR)
    group by ...
    ) , daily AS (
    select
     ...
    from {| dataSourceTableName .Report.Inputs.SourceTable |}
    where labels['timestamp'] >=  '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND labels['timestamp'] <  '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
    group by ...
    )
    select
    *
    from {| .Report.Inputs.SelectTable |}
```
```
---
apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: base-daily
spec:
  generationQuery: "..."
  schedule:
    period: "daily"
  reportingStart: "2019-03-01T00:00:00Z"
  inputs:
  - name: SourceTable
    value: ...
  - name: SelectTable
    value: daily
  #overwriteExistingData: true
---
apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: base-today
spec:
  generationQuery: "...
  schedule:
    period: "hourly"
  reportingStart: "2019-03-12T00:30:00Z"
  #gracePeriod: "30m"
  inputs:
  - name: SourceTable
    value: ...
  - name: SelectTable
    value: today
  overwriteExistingData: true
```

```
query: |
    with union_table as (
    with union_table_daily as (
        select  * from {| reportTableName  "base-daily" |}
        where dt < current_date
        ),
        union_table_today as (
        select  * from {| reportTableName  "base-today" |}
        where dt >= current_date
        )
        
    select * from union_table_daily
    union all 
    select * from union_table_today
    )
    select 
    *
    from union_table
  reportDataSources:
  - ...
  view:
    disabled: false
```


When I query daily, I can not get the data today, so I separated it into daily and today and combined it into a view.

Thank you .
