### ISSUE TITLE
release >4.1 and useServiceAccountCA: false

### ISSUE THREAD

**Issue by mmariani** [operator-framework/operator-metering#782]
Hello!

My Kubernetes cluster (Canonical, w/ MaaS/Juju) had issues, and I decided to reinstall it with a new metering operator. I see HDFS is not recommended anymore, but the documentation seems improved. Back to the Rook table, I learned how to create CephFS volumes to support ReadWriteMany. So far so good.

This is the new configuration I tried:

```
apiVersion: metering.openshift.io/v1alpha1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      config:
        prometheusURL: "http://prometheus-prometheus-oper-prometheus.monitoring:9090/"
        prometheusCertificateAuthority:
          useServiceAccountCA: false
          configMap:
            enabled: false
        tls:
          api:
            enabled: false
  presto:
    spec:
      presto:
        securityContext:
          fsGroup: 0
        worker:
          replicas: 0
      hive:
        securityContext:
          fsGroup: 0
  storage:
    hive:
      type: "sharedPVC"
      sharedPVC:
        claimName: "cephfs-metering"
```

I use the plain Prometheus chart without kube-prometheus.

And my install.sh:

```
METERING_NAMESPACE=metering
PROMETHEUS_NAMESPACE=monitoring
METERING_CR_FILE=$(pwd)/metering-custom.yaml
./operator-metering/hack/install.sh
```

The latter part of my configuration (sharedPVC) is honored, but the operator keeps looking for service-ca.crt and fails.
Is the master branch supposed to be, if not stable, installable without OpenShift? Can we expect a stable 4.2/4.3 soon?

I am now restoring the 4.1 version, but could do without the additional complexity of HDFS and would like to keep the data volume next time I upgrade.

Thank you again for your work.

**Comment by mmariani** [comment]
Update: I get the same error with release-4.1 and the old configuration.

```
time="2019-06-27T15:52:04Z" level=fatal msg="error occurred while the reporting-operator
was running" app=metering error="stat /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt:
no such file or directory"
```

```
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      config:
        prometheusURL: "http://prometheus-prometheus-oper-prometheus.monitoring:9090/"
        prometheusCAFile: ""
        tls:
          enabled: false
        metricsTLS:
          enabled: false
[...]
```

**Comment by chancez** [comment]
We're tried to the Openshift release cycle and other Kubernetes support is best-effort for the time-being since we don't currently have enough resources to devote to supporting both equally. 

Additionally, we're still in an alpha state, and will be going GA soon, so there will be breakage and no support upgrade paths until we go GA.

It should be possible to configure most of the Openshift options to be disabled, but it's not necessarily well documented since we only test on Openshift currently.

When did you try to install from master/release-4.2? Yesterday we merged a PR (#771) which changes the configuration schema for the `reporting-operator` configuration, so it's possible you were effected by that. 

We don't have any real documentation on the options you're trying to set because we're still figuring out the best way to design the configuration API, but at this point we think we have it finalized. Since we don't have documentation on it, you can look at the https://github.com/operator-framework/operator-metering/blob/master/charts/openshift-metering/values.yaml to get an idea of the structure.

I think this may be close to what you're looking for, but I haven't tested it:
```
apiVersion: metering.openshift.io/v1alpha1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  tls:
    enabled: false

  reporting-operator:
    spec:
      config:
        prometheus:
          url: "http://prometheus-prometheus-oper-prometheus.monitoring:9090/"
          certificateAuthority:
            useServiceAccountCA: false
          metricsImporter:
            auth:
              # depends on how you setup auth for Prometheus
              useServiceAccountToken: false

        tls:
          api:
            enabled: false
  presto:
    spec:
      presto:
        securityContext:
          fsGroup: 0
        worker:
          replicas: 0
      hive:
        securityContext:
          fsGroup: 0
  storage:
    hive:
      type: "sharedPVC"
      sharedPVC:
        claimName: "cephfs-metering"
```

**Comment by mmariani** [comment]
> We're tried to the Openshift release cycle and other Kubernetes support is best-effort for the time-being since we don't currently have enough resources to devote to supporting both equally.

Of course, and I am happy to help to ensure compatibility with my configuration. I'm still learning k8s, wish I could do more.

> When did you try to install from master/release-4.2? Yesterday we merged a PR (#771) which changes the configuration schema for the reporting-operator configuration, so it's possible you were effected by that.

It may have been that, indeed.

> Since we don't have documentation on it, you can look at the https://github.com/operator-framework/operator-metering/blob/master/charts/openshift-metering/values.yaml to get an idea of the structure.
> I think this may be close to what you're looking for, but I haven't tested it:

Thanks! I have finally found a working configuration.

For reference, prometheus was installed with `helm install --namespace monitoring stable/prometheus-operator`

```
apiVersion: metering.openshift.io/v1alpha1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:

  reporting-operator:
    spec:
      config:
        prometheus:
          url: "http://prometheus-prometheus-oper-prometheus.monitoring:9090/"
          certificateAuthority:
            useServiceAccountCA: false
          metricsImporter:
            auth:
              useServiceAccountToken: true
              tokenSecret:
                enabled: false
        tls:
          api:
            enabled: false
[...]
```
