### ISSUE TITLE
hive PV permissions

### ISSUE THREAD

**Issue by mmariani** [operator-framework/operator-metering#818]
Hello!

I have been having permission issue in hive-metastore: the mounted directories have mode `rwxrws---` (root.root) and the user is hadoop (1002).
The volumes are dynamically provided by rook/ceph.

I had to change `charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml`. I'm not committing anything, you surely know of a cleaner way.

```
      initContainers:
      - name: chown-metastore
        image: alpine
        command:
        - chown
        - -R
        - 1002:1002
        - /var/lib/hive
        volumeMounts:
        - name: hive-metastore-db-data
          mountPath: /var/lib/hive
      - name: chown-warehouse
        image: alpine
        command:
        - chown
        - -R
        - 1002:1002
        - {{ .Values.hive.spec.config.sharedVolume.mountPath }}
        volumeMounts:
        - name: hive-warehouse-data
          mountPath: {{ .Values.hive.spec.config.sharedVolume.mountPath }}
```
