### ISSUE TITLE
error syncing reportDataSource

### ISSUE THREAD

**Issue by mmariani** [operator-framework/operator-metering#821]
Hello

I am now running the upstream 4.2 images, my deployment is now successful, database tables are created, but I cannot see data in any of them.

There is data in /user/hive/warehouse/metering.db (10k files in a few minutes), but all selects in the metering schema return empty sets.

I get these errors:

```
time="2019-07-10T10:03:05Z" level=info msg="syncing ReportDataSource metering/pod-usage-memory-bytes" app=metering component=reportDataSourceWorker logID=cOM1SY4t6h
time="2019-07-10T10:03:05Z" level=info msg="existing Prometheus ReportDataSource discovered, tableName: hive.metering.datasource_metering_pod_usage_memory_bytes" app=metering component=reportDataSourceWorker logID=cOM1SY4t6h namespace=metering reportDataSource=pod-usage-memory-bytes
time="2019-07-10T10:03:05Z" level=info msg="no data in table hive.metering.datasource_metering_pod_usage_memory_bytes: backfilling from 2019-07-10 08:03:05.745432195 +0000 UTC until 2019-07-10 10:03:05.745432195 +0000 UTC" app=metering chunkSize=5m0s component=PrometheusImporter logID=mlXIFoUQic namespace=metering reportDataSource=pod-usage-memory-bytes stepSize=1m0s tableName=hive.metering.datasource_metering_pod_usage_memory_bytes
time="2019-07-10T10:03:05Z" level=warning msg="time range 2019-07-10 08:03:05.745432195 +0000 UTC to 2019-07-10 10:03:05.745432195 +0000 UTC exceeds PrometheusImporter MaxQueryRangeDuration 10m0s, newEndTime: 2019-07-10 08:13:05.745432195 +0000 UTC" app=metering chunkSize=5m0s component=PrometheusImporter logID=mlXIFoUQic namespace=metering reportDataSource=pod-usage-memory-bytes stepSize=1m0s tableName=hive.metering.datasource_metering_pod_usage_memory_bytes
time="2019-07-10T10:03:08Z" level=error msg="error collecting metrics" app=metering chunkSize=5m0s component=PrometheusImporter endTime="2019-07-10 10:03:05.745432195 +0000 UTC" error="failed to store Prometheus metrics into table hive.metering.datasource_metering_pod_usage_memory_bytes for the range 2019-07-10 08:03:00 +0000 UTC to 2019-07-10 08:08:00 +0000 UTC: failed to store metrics into presto: presto SQL error: presto: query failed (200 OK): \"io.prestosql.spi.PrestoException: Unable to rename from file:/tmp/presto-reporting-operator/eec7d131-f534-41a2-91ee-78a237dba74b/dt=2019-07-10 to file:/user/hive/warehouse/metering.db/datasource_metering_pod_usage_memory_bytes/dt=2019-07-10: target directory already exists\"" logID=mlXIFoUQic namespace=metering reportDataSource=pod-usage-memory-bytes startTime="2019-07-10 08:03:05.745432195 +0000 UTC" stepSize=1m0s tableName=hive.metering.datasource_metering_pod_usage_memory_bytes
time="2019-07-10T10:03:08Z" level=error msg="error syncing ReportDataSource \"metering/pod-usage-memory-bytes\", adding back to queue" ReportDataSource=metering/pod-usage-memory-bytes app=metering component=reportDataSourceWorker error="ImportFromLastTimestamp errored: failed to store Prometheus metrics into table hive.metering.datasource_metering_pod_usage_memory_bytes for the range 2019-07-10 08:03:00 +0000 UTC to 2019-07-10 08:08:00 +0000 UTC: failed to store metrics into presto: presto SQL error: presto: query failed (200 OK): \"io.prestosql.spi.PrestoException: Unable to rename from file:/tmp/presto-reporting-operator/eec7d131-f534-41a2-91ee-78a237dba74b/dt=2019-07-10 to file:/user/hive/warehouse/metering.db/datasource_metering_pod_usage_memory_bytes/dt=2019-07-10: target directory already exists\"" logID=cOM1SY4t6h
```
with the following configuration

```
apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: operator-metering
spec:
  tls:
    enabled: false

  reporting-operator:
    spec:
      route:
        enabled: false

      config:
        prometheus:
          url: "http://prometheus-prometheus-oper-prometheus.monitoring:9090/"
          certificateAuthority:
            useServiceAccountCA: false
          metricsImporter:
            auth:
              useServiceAccountToken: true
              tokenSecret:
                enabled: false

        tls:
          api:
            enabled: false

        promsumChunkSize: "5m"
        promsumPollInterval: "5m"
        promsumStepSize: "60s"
  hive:
    spec:
      securityContext:
        fsGroup: 0
  presto:
    spec:
      securityContext:
        fsGroup: 0
  storage:
    hive:
      type: "sharedPVC"
      sharedPVC:
        claimName: "hive-shared-fs"
```
In beeline, I have another error on the *_raw tables (all the other tables show as empty):

```
Connecting to jdbc:hive2://127.0.0.1:10000/metering;auth=noSasl
Connected to: Apache Hive (version 2.3.3)
Driver: Hive JDBC (version 2.3.3)
Transaction isolation: TRANSACTION_REPEATABLE_READ
Beeline version 2.3.3 by Apache Hive
0: jdbc:hive2://127.0.0.1:10000/metering> select * from datasource_metering_pod_cpu_usage_raw;
Error: Error while compiling statement: FAILED: SemanticException line 1:17 cannot recognize input near '<EOF>' '<EOF>' '<EOF>' in definition of VIEW datasource_metering_pod_cpu_usage_raw [
/* Presto View */
] used as datasource_metering_pod_cpu_usage_raw at Line 1:14 (state=42000,code=40000)
```

How can I debug further?
