### ISSUE TITLE
metering error service-ca.crt: no such file or directory

### ISSUE THREAD

**Issue by ivanguravel** [operator-framework/operator-metering#891]
Hello!

I have aws eks with version 1.12.8 and i'm trying to apply `operator-metering` to that.

i use `release-4.1` branch and my metering-config.yaml looks like this:

```yaml
apiVersion: metering.openshift.io/v1alpha1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      config:
        prometheusURL: "http://prom-prometheus-operator-prometheus.monitoring.svc.cluster.local:9090/"
        prometheusCAFile: ""
        tls:
          enabled: false
        metricsTLS:
          enabled: false
  presto:
    spec:
      presto:
        securityContext:
          fsGroup: 0
      hive:
        securityContext:
          fsGroup: 0
  hdfs:
    spec:
      securityContext:
        fsGroup: 0
```

after 2 mins all pods are ok instead of `reporting-operator`:

```
kubectl logs reporting-operator-5575798554-6927d -n metering
time="2019-08-09T19:01:53Z" level=info msg="setting log level to info" app=metering
time="2019-08-09T19:01:53Z" level=info msg="watching namespaces [] for metering.openshift.io resources" app=metering
time="2019-08-09T19:01:53Z" level=info msg="starting Metering operator" app=metering
time="2019-08-09T19:01:53Z" level=info msg="starting Prometheus metrics & pprof servers" app=metering
time="2019-08-09T19:01:53Z" level=info msg="setting up DB clients" app=metering
time="2019-08-09T19:01:53Z" level=fatal msg="error occurred while the reporting-operator was running" app=metering error="stat /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt: no such file or directory"
```
i saw this 1 pr: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/178 , it prepared on March and commits to `release-4.1` were stopped 3 month ago. I suppose that `release-4.1` should contains that pr.

what do you think about that ? could you please give me some advices how to resolve current issue?

Thanks a lot!

**Comment by chancez** [comment]
You need to set `spec.reporting-operator.authProxy.enabled` to false. This leverages an internal CA cert and functionality available only in Openshift.

**Comment by ivanguravel** [comment]
@chancez   tested , but the same :(


'''
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      authProxy:
        enabled: false
      config:
        prometheusURL: "http://prom-prometheus-operator-prometheus.monitoring.svc.cluster.local:9090/"
        prometheusCAFile: ""
        tls:
          enabled: false
        metricsTLS:
          enabled: false
  presto:
    spec:
      presto:
        securityContext:
          fsGroup: 0
      hive:
        securityContext:
          fsGroup: 0
  hdfs:
    spec:
      securityContext:
        fsGroup: 0
'''

**Comment by ivanguravel** [comment]
@chancez   i fixed it for `release-4.1`:

```
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      authProxy:
        enabled: false
      config:
        prometheusCertificateAuthority:
          useServiceAccountCA: false
        prometheusURL: "http://prom-prometheus-operator-prometheus.monitoring.svc.cluster.local:9090/"
        prometheusCAFile: ""
        tls:
          enabled: false
        metricsTLS:
          enabled: false
  presto:
    spec:
      presto:
        securityContext:
          fsGroup: 0
      hive:
        securityContext:
          fsGroup: 0
  hdfs:
    spec:
      securityContext:
        fsGroup: 0
```

i did that with helps: `config: prometheusCertificateAuthority: useServiceAccountCA: false` . i found that inside one of related docs. could you please add that to something like `known issues` for release.

Thanks a lot for your help!
