### ISSUE TITLE
Unable to get hdfs-datanode running with OC 4.1

### ISSUE THREAD

**Issue by heoneal** [operator-framework/operator-metering#904]
Hi,

I tried to do the simplest install of metering that I could from https://github.com/operator-framework/operator-metering/releases/tag/0.14.0 for a basic POC in my OC 4.1 cluster. I am unable to get the hdfs-datanode-0 pod to run successfully. I am using PV in NFS for the POC. Attached is the log from my hdfs node. I am unsure as to why it's getting this failure. 

Should I move to working out of the current master instead?

I ran operator-metering-0.14.0/hack/openshift-install.sh metering.yaml, where metering.yaml is from default.yaml in https://github.com/operator-framework/operator-metering/releases/tag/0.14.0. 

[hdfs-datanode-0-hdfs-datanode.log](https://github.com/operator-framework/operator-metering/files/3510819/hdfs-datanode-0-hdfs-datanode.log)

**Comment by heoneal** [comment]
I think this may be a byproduct of RedHat CoreOS forcing a ReadOnly root file system. When the pod tries to modify /hadoop/dfs/data, it get's the Operation not permitted failure. I don't know why the hdfs pod is trying to write to the root file system though.

**Comment by chancez** [comment]
0.14.0 is quite old and thing's have changed enormously, you should consider installing from the 4.1 Operator Hub (https://github.com/operator-framework/operator-metering/blob/release-4.1/Documentation/olm-install.md) or a manual install which installs from the latest master builds (https://github.com/operator-framework/operator-metering/blob/master/Documentation/manual-install.md).

The 4.1 install is going to become deprecated in 4.2 as we've made some breaking changes and 4.2 is the first GA/stable release which will be available. The 4.2 install will also be available via OLM once 4.2 is out. 

You may wish to use the manual install if you want to try the latest today, but note that it is only supported on a best-effort basis.

**Comment by heoneal** [comment]
Chance,

Thank you for the quick reply. I have attempted to run using the OLM 4.1 install from Operator Hub. I have gone through what I think is a vanilla install of an on-prem OpenShift 4.1 cluster. This is a fairly new cluster that has no special "on-prem" adjustments made. I am using the default configuration file for operator metering : https://github.com/operator-framework/operator-metering/blob/release-4.1/manifests/metering-config/default.yaml

```javascript
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
  namespace: "metering"
spec: {}
```
I am seeing the errors in the attached log with this new OLM install. Do you recommend I try to do a manual operator install from latest master? I am using PV that are on NFS, but they appear to be accepted appropriately. I am unsure if this could be related to Secure Security Contexts and privleges needed by the HDSF node based on seeing comments in another issue request [https://github.com/operator-framework/operator-metering/issues/557](url)

```
>oc get pv
NAME     CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                             STORAGECLASS   REASON   AGE
pv0001   100Gi      RWX            Retain           Bound    openshift-image-registry/image-registry-storage                           18d
pv0002   5Gi        RWO            Recycle          Bound    metering/hive-metastore-db-data                                           3h1m
pv0003   5Gi        RWO            Recycle          Bound    metering/hdfs-datanode-data-hdfs-datanode-0                               31m
pv0004   5Gi        RWO            Recycle          Bound    metering/hdfs-namenode-data-hdfs-namenode-0                               31m
```
```
>oc get pods
NAME                                  READY   STATUS    RESTARTS   AGE
hdfs-datanode-0                       0/1     Error     5          6m16s
hdfs-namenode-0                       1/1     Running   0          6m15s
hive-metastore-0                      1/1     Running   0          6m14s
hive-server-0                         1/1     Running   0          6m13s
metering-operator-69b57846f7-xv2n6    2/2     Running   0          9m34s
presto-coordinator-7ccdd56454-6gldp   1/1     Running   0          6m17s
reporting-operator-856cb948fb-s5bfz   1/1     Running   0          6m17s
```

[hdfs-datanode-0-hdfs-datanode (1).log](https://github.com/operator-framework/operator-metering/files/3517248/hdfs-datanode-0-hdfs-datanode.1.log)

**Comment by chancez** [comment]
If your using NFS, it sounds like the permissions aren't what HDFS expects. Since your using NFS, I doesn't really make sense to be using HDFS at all, so instead of fixing HDFS, I recommend you go the route of configuring metering to use NFS directly and disable HDFS: https://github.com/operator-framework/operator-metering/blob/release-4.1/Documentation/configuring-storage.md#using-shared-volumes-for-storage

Otherwise, you could fix the underlying permissions of the PV so that HDFS doesn't error, or override the expected permissions value (this may not work though). Currently the value expected is `775` (the normal permissions for a PVC created by Openshift). You could override it by setting `spec.hdfs.spec.config.datanodeDataDirPerms` in your Metering CR to something like `"770"` (it must be a number in a string).

**Comment by heoneal** [comment]
Chance,

I modified shared-storage and installed via OLM. I'm a little confused that I am still seeing the hdfs pods, even with the hdfs disabled. Should I still be seeing them? 

This is my modified https://github.com/operator-framework/operator-metering/blob/release-4.1/manifests/metering-config/shared-storage.yaml
```
apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  defaultStorage:
    type: "hive"
    hive:
      # instructs reporting-operator to create a new database in Hive
      unmanagedDatabase: false
      # feel free to adjust the database name and location
      databaseName: "metering-nfs"
      location: "/user/hive/warehouse"

  presto:
    spec:
      config:
        sharedVolume:
          enabled: true
          storage:
            # change REPLACEME to the name of your PVC
            #persistentVolumeClaimStorageClass: REPLACEME
            # mountPath must match the value of the location specified above.
            mountPath: "/user/hive/warehouse"
      hive:
        config:
          # set to false when spec.hdfs.enabled is false
          useHdfsConfigMap: false
          # Replace this with your path
          metastoreWarehouseDir: "/user/hive/warehouse"
  hdfs:
    enabled: false
```

```
>oc get pods
NAME                                  READY   STATUS     RESTARTS   AGE
hdfs-datanode-0                       0/1     Init:0/1   0          2m2s
hdfs-namenode-0                       0/1     Pending    0          2m
hive-metastore-0                      1/1     Running    0          119s
hive-server-0                         0/1     Running    0          118s
metering-operator-65957cc-f8lgw       2/2     Running    0          9m35s
presto-coordinator-64f9b8746c-bmqkn   1/1     Running    0          2m3s
reporting-operator-64cddbb79f-7xtb2   1/1     Running    0          2m3s
```
