### ISSUE TITLE
 How to install the latest version in kubernetes?

### ISSUE THREAD

**Issue by JooyoungJeong** [operator-framework/operator-metering#963]
Hi. 

My currently metering version : v0.12.0

I want to install the latest master branch or latest metering release version in kubernetes(v1.12.3)
Is v4.x.x  for openshift and  v0.1x.0 for kubernetes ?

How to install the latest version in kubernetes?

Thank you

**Comment by timflannagan1** [comment]
@JooyoungJeong you can install the latest upstream version of metering using OLM through [OperatorHub.io](https://operatorhub.io/operator/metering-upstream). 

For the release-4.2 branch, we added support for vanilla kubernetes installations, and you would need to run the `./hack/upstream-install.sh` script, and configure storage and the `reporting-operator.spec.config.prometheus.url` field, e.g.:

```yaml
apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      config:
        prometheus:
          # update this field
          url: "http://prometheus-k8s.monitoring.svc:9090"

  unsupportedFeatures:
    enableHDFS: true

  storage:
    type: "hive"
    hive:
      type: "hdfs"
      hdfs:
        namenode: "hdfs-namenode-0.hdfs-namenode:9820"
```

**Comment by JooyoungJeong** [comment]
@timflannagan1 Thank you for your help. 

I succeeded in installation by referring to MeteringConfig which you informed me.
```
Kubernetes: 1.12
metering: git checkout release-4.2    
(release-4.2 5ca69bb Merge pull request #945 from chancez/dep_ignore_test2json)
```
But I want to using S3.   So I tried installing using MeteringConfig  like below but failed.
Should I use a different version?

Thank you

```
apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  disableOCPFeatures: true

  reporting-operator:
    spec:
      config:
        prometheus:
          # update this field
          url: "http://prometheus-operator-prometheus.default.svc:9090"
  storage:
    type: "hive"
    hive:
      type: "s3"
      s3:
        bucket: "test-metering-test2"
        secretName: "my-aws-secret"
        createBucket: false
        region: "us-west-2"
```
test-metering-test2 is a pre-created bucket in aws s3. 

```
operator-metering$ ./hack/upstream-install.sh 

operator-metering$ kubectl  get pod  -n metering
NAME                                  READY     STATUS                  RESTARTS   AGE
hive-metastore-0                      0/1       CrashLoopBackOff        6          10m
hive-server-0                         0/1       CrashLoopBackOff        6          10m
metering-operator-55c7bf799c-qm5z4    2/2       Running                 0          12m
presto-coordinator-0                  0/1       Init:CrashLoopBackOff   6          10m
reporting-operator-6986d5bbd7-6tzlk   0/1       CrashLoopBackOff        6          9m
```

```
$ kubectl  describe pod hive-server-0   -n metering
....
Init Containers:
  copy-starter-hive:
    Container ID:  docker://d689acf01b6eaf19ef4616550dd9ccd56a905f23048a37428e03f09b36506601
    Image:         quay.io/coreos/hive:release-4.2
    Image ID:      docker-pullable://quay.io/coreos/hive@sha256:34ca84392bbf21118c767bb0f60846bac49acc50d711e89ac0d144a988f99682
    Port:          <none>
    Host Port:     <none>
    Command:
      /hive-scripts/copy-hadoop-config.sh
....
Events:
  Type     Reason     Age                From                                                  Message
  ----     ------     ----               ----                                                  -------
  Normal   Scheduled  17m                default-scheduler                                     Successfully assigned metering/hive-server-0 to ip-172-20-49-162.us-west-2.compute.internal
  Normal   Pulling    16m                kubelet, ip-172-20-49-162.us-west-2.compute.internal  pulling image "quay.io/coreos/hive:release-4.2"
  Normal   Pulled     16m                kubelet, ip-172-20-49-162.us-west-2.compute.internal  Successfully pulled image "quay.io/coreos/hive:release-4.2"
  Normal   Created    16m                kubelet, ip-172-20-49-162.us-west-2.compute.internal  Created container
  Normal   Started    16m                kubelet, ip-172-20-49-162.us-west-2.compute.internal  Started container
  Normal   Pulling    16m (x4 over 16m)  kubelet, ip-172-20-49-162.us-west-2.compute.internal  pulling image "quay.io/coreos/hive:release-4.2"
  Normal   Pulled     16m (x4 over 16m)  kubelet, ip-172-20-49-162.us-west-2.compute.internal  Successfully pulled image "quay.io/coreos/hive:release-4.2"
  Normal   Created    16m (x4 over 16m)  kubelet, ip-172-20-49-162.us-west-2.compute.internal  Created container
  Warning  Failed     16m (x4 over 16m)  kubelet, ip-172-20-49-162.us-west-2.compute.internal  Error: failed to start container "hiveserver2": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"setenv: invalid argument\"": unknown
  Warning  BackOff    1m (x73 over 16m)  kubelet, ip-172-20-49-162.us-west-2.compute.internal  Back-off restarting failed container
```

```
operator-metering$ kubectl  logs metering-operator-55c7bf799c-qm5z4    -n metering --tail=100  -c ansible
PLAY RECAP *********************************************************************
localhost                  : ok=160  changed=9    unreachable=0    failed=0    skipped=140  rescued=0    ignored=0   

Wednesday 02 October 2019  07:42:26 +0000 (0:00:00.031)       0:03:10.040 ***** 
=============================================================================== 
meteringconfig -------------------------------------------------------- 184.28s
gather_facts ------------------------------------------------------------ 5.62s
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
total ----------------------------------------------------------------- 189.89s
Playbook run took 0 days, 0 hours, 3 minutes, 9 seconds
ubuntu@ip-172-31-33-231:~/work/operator-metering$ 
```

**Comment by timflannagan1** [comment]
@JooyoungJeong is the "my-aws-secret" base64 encoded?

**Comment by JooyoungJeong** [comment]
@timflannagan1 
The access id shown when creating the aws key in aws(IAM).
```
apiVersion: v1
kind: Secret
metadata:
  name: my-aws-secret
data:
  aws-access-key-id: "AKI***********JAQ"
  aws-secret-access-key: "pgO**************40*******+et******/M*****"
```

Thank you

**Comment by pruan-rht** [comment]
@JooyoungJeong, you need to `base64` encode the `key-id` and `access-key`.  Here's the command to do it `echo -n '<your_aws_key>' | base64`

**Comment by pruan-rht** [comment]
@chancez I think we can close this issue as encoding the creds was able to resolve another person's issue with the same symptom.

**Comment by JooyoungJeong** [comment]
@pruan-rht  
thank you~
I succeeded in installation. And i succeeded in installation using "s3Compatible"

my metering-custom.yaml
```
apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  disableOCPFeatures: true
  reporting-operator:
    spec:
      config:
        prometheus:
          # update this field
          url: "<ip>"
  hive:
    
  storage:
    type: "hive"
    hive:
      type: "s3Compatible"
      s3Compatible:
        bucket: "metering"
        secretName: "my-aws-secret"
        createBucket: false
        endpoint: "<ip>"
```
